name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "3-53/60 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "kenzok8@gmail.com"
          git config --local user.name "kenzok8"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.1
        with:
          token: ${{ github.token }}
          repository: kenzok8/openwrt-packages
          retain_days: 1
          keep_minimum_runs: 1

      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
         
